### ISSUE TITLE
Fernotron Protocol

### ISSUE THREAD

**Issue by ovl666** [zwiebert/tronferno-mcu#1]
Hello Bert, 
at github I can only set up an issue - there's no mail or message I found.

Do you have further information how to create Fernotron sending protocol with given ID of 2411?
I tried to figure out by source code, but I'm not realy shure if I'll get it correct.

How is "sun-inst" to be used?

Do you also found out, how to set end positions with remote commands?

I have all motor nd remote controller IDs with me so - if I got you right - I do not need to analyze with a receiver, correct?

I think FHEM Forum will be interested in your development.

Great Job and Thanks

Oliver

**Comment by zwiebert** [comment]
Hallo Oliver,

just found your message. I'm new on GitHub ... sorry.

There should be some text files on my hard disk where I described to myself the protocol.  I add it as documentation to the repository later.

sending "sun-inst" should let the shutter motor  memorize its current position.  later when sending "sun-down", the shutter will go down and stop at that position.  This works with the motors with builtin RF-Receivers (it knows it own position all the time).   For motors with external receivers,  one may need to follow the manual of the fernotron sun sensor.  I guess it works by measuring the time to reach the position instead the position directly.

EDIT:   Setting end positions.  the commands are in fer_prog.h (fer_cmd_EndPosUP ...), but are not in the CLI.   I just looked how the 2411 does it.  The up or down button has to be held down.  It sends limit-up or limit-down when pressing the key for 3 times and stop (3x) when releasing the key.
Seems very dangerous to use from the MCU.  If for some reason stop is not send or received, the motor will go beyond the end positions and may damage the shutter. I'll may test this later with a spare motor I have.   I added the commands to the CLI but disabled them for now. 


Not sure about the motor IDs.  There was a bug in my software. With the current version it seems to work sending up, down, stop commands using the motor ID (9 followed by 5 digit hex number printed on the motor). 

I added a perl script in repository tronferno-fhem, which allows extracting the  central unit ID from these raw strings from the FHEM/SIGNALduino logfile.

Had FEHM installed a few days ago for the first time.  Should be not to hard to add a module.  I guess timer programming can not made to work with sending RAW strings by the SIGNALduino. They would be very long.  So I plan to write a module for my hardware.  And also write some code to send simple commands vie SIGNALduino.  That perl script can do that already.  

Hope I could help.  I will add the documentation later.  Please be patient.

Bert

**Comment by zwiebert** [comment]
... you are right about these end positions.  There are commands for end-positions in fer_prog.h: 
	fer_cmd_EndPosUP,
	fer_cmd_endPosDOWN,

but they are missing in the CLI.  I'll add them ASAP.   Thanks for reporting.
