### ISSUE TITLE
save parameter in a backup file

### ISSUE THREAD

**Issue by franki023** [zwiebert/tronferno-mcu#10]
Bert thank you for this fantasitc software,
is it possible to save all parameters in a backup file?
Frank

**Comment by zwiebert** [comment]
Hello Frank,

Thanks for your feedback.   It should be possible to save the entire NVS partition of the ESP32 using esptool (the tool which was used for flashing the firmware initially). 

Name,   Type, SubType, Offset,  Size, Flags
nvs,      data, nvs,      0x9000,   0x6000,      <---- settings are saved here
storage,  data, spiffs,  0x12000,  0xee000,  <---- some timer data is saved here as files? (IIRC)

I startet to implement some Backup functionality some time ago, where the settings are saved into a JSON file which then can be downloaded from the internal webserver.  This functionality can be accessed from the webbrowser via the ?->Backup tab.  This tab is only visible in the "Expert" GUI.  (Choose Expert in the rightmost tab).  Currently it saves some data related to each shutter (timers, names, ...).  If I have the time, I will extend it to save all the settings data.

-Bert

**Comment by franki023** [comment]
Hello Bert,
thank you that is exactly what I need.
I looked at al tabs but was not able to find the backup tab.
The user is experte visible on ##> my version is the lates 0.12.1.44.
My I am blind can you give me a hint.
Thanks in advance Frank
[Empfänger Sender.pdf](https://github.com/zwiebert/tronferno-mcu/files/14200087/Empfanger.Sender.pdf)

**Comment by zwiebert** [comment]
The Backup tab should be under the "?" tab. The sub tabs there should be OTA | HomeServer|Backup|OnlineDocu.

I'm not sure if you are really using the same version 0.12.1.44 like I do?  The "##>" (Expert "shell prompt") was replaced by a Computer-Icon in this version.  The "##>" was on a previous version.  I re-downloaded the version via the OTA tab, to make sure the version on the server is correct, and found no problem.

The version can be seen on the bullet point list under the ?->OTA tab, and should look like this:

MCU type: esp32
Version: tronferno-mcu-0.12.1.44
Build Date: Sep--4-2023T15:57:41

If there are really 2 different versions with the same number, at least the build date should be different. Please try and re-update the firmware using the OTA tab.

**Comment by franki023** [comment]
you are right my version is not the latest Version: tronferno-mcu-0.12.1.
I have updated to the latest version and now the backup tab is visible.
Tanks a lot frank

**Comment by zwiebert** [comment]
You are welcome.  Thanks for the feedback.  Its obvious, the bad user interface in the OTA tab is to blame for the confusion about the version number.  I will work on it.

-Bert

**Comment by franki023** [comment]
you do a fantastic work ;-)
frank

**Comment by zwiebert** [comment]
Thanks. In the latest beta version "1.12.2.1"  the backup/restore functionality does now cover more data.  It should now save and restore anything except passwords.

-Bert
