### ISSUE TITLE
CC1101 GDO2 not connected. Is it connected to the configured GPIO?

### ISSUE THREAD

**Issue by jochenpa** [zwiebert/tronferno-mcu#11]
Hi Bert

Since about 3 betas the OTA Firmware Update page shows this error:
"CC1101 GDO2 not connected. Is it connected to the configured GPIO?"

The Option "Funkmodule" is set to "RX & TX", so it should not try to connect to CC101 ...

Thank you

Jochen Pawletta

**Comment by zwiebert** [comment]
Hello Jochen, thank you for reporting this. 

In version 1.12.4.11  it is fixed.  It was luckily only the error-test which was executed when it should have not.  While working on it, I found two other minor problems, which were also confusing for the user, inlcuding myself.  Works much better now. Thanks.

-Bert
