### ISSUE TITLE
ESP8266 Pinout

### ISSUE THREAD

**Issue by ovl666** [zwiebert/tronferno-mcu#2]
Hello Bert,

in Doc you wrote 
`    Prepare Hardware:`
`       esp8266 (development board) connected to USB on your PC`
`        RF receiver connected to D1 on the MCU board`
`        RF transmitter connected to D2`

It might be easier to assign GPIO Pins so:
`       RF receiver connected to GPIO5`
`        RF transmitter connected to GPIO4`

**Comment by zwiebert** [comment]
Hello Oliver, thanks for reporting. You are right of course.

I'm using 2 different kinds of boards myself and GPIO4 is called D2 on one and D4 on the other.
