### ISSUE TITLE
Header fields are too long for server to interpret

### ISSUE THREAD

**Issue by trombose009** [zwiebert/tronferno-mcu#6]
Hey, 

wenn ich meine config in der weboberfläche speicher, dann kommt die Meldung: 
Header fields are too long for server to interpret
Ist das ok?
Er scheint alles zu speichern.

**Comment by zwiebert** [comment]
Hallo,
die Fehlermeldung tritt m.W. auf, wenn eine vom Web-Browser gesendete Header-Zeile länger ist, als das im Web-Server konfigurierte Maximum.  Ich hatte das Limit mal hochgesetzt, weil Microsoft-Edge solch zu langen Header-Zeilen gesendet hat.   Ist also eine Frage der Kombination aus Firmware-Version und welcher Web-Browser. Welche Versionen nutzt du?

Wundert mich aber, dass es trotzdem funktioniert.  Der Request dürfte bei dieser Fehlermeldung auch gar nicht ausgeführt werden.  Könnte aber sein, weil ein Teil der Daten über Websocket statt HTTP-Requests übertragen wird?

Welche Versionen von Firmware und Web-Browser benutzt du?

**Comment by trombose009** [comment]
Also, ich stelle gerade fest, wenn ich mich vom handy (android/chrome) über http einloggen möchte, kommt zwar benutzername/passwort abfrgae, dann aber der besagte fehler. also es erscheint dann keine Oberfläche. mache ich es am Computer mit chrome, komme ich problemlos auf die Oberfläche. 
Ok. ist ja erstmal nicht so dramatisch. 
Ich teste erst einmal ein bisschen weiter.
Firmware Info
MCU type: esp32
firmware version: tronferno-mcu-0.10.10
firmware build date: Jun--2-2020T21:31:03
boot-count: 5

**Comment by trombose009** [comment]
ok, nach einem Firmware Upgrade scheint alles perfekt zu funktionieren. Danke!
