### ISSUE TITLE
Pairing mit Sonnensensoren klappt nicht mehr

### ISSUE THREAD

**Issue by jochenpa** [zwiebert/tronferno-mcu#7]
Hallo und frohes neues Jahr!

Ich hatte mal alle Sonnensensoren und Fernbedienungen in der Firmware 0.10.10 gelistet, es war aber eine "komische" ID dabei die ich los werden wollte.
Ich habe dann Unpair gedrückt, und dann waren irgendwie alle IDs weg.

Jetzt würde ich gerne die Sonnensensoren und Fernbedienungen dort wieder hinzufügen, das klappt aber weder mit der Firmware 0.10.10 noch mit der 0.11.42.
Es ist als ob keine Codes/IDs empfangen würden.
Das kann aber nicht sein, weil die MCU reagiert, wenn ich auf der Fernbedienung die Knöpfe drücke.
Es wird dann ganz normal der damit verbundene Motor auf- und ab-gefahren, und dies wird in der MCU angezeigt.

Für mich scheint es, als ob die Konfiguration an der Stelle "strubbelig" ist.
Kann man die interne Konfiguration der MCU irgendwie löschen?
Im Idealfall vielleicht auch nur den Teil, der für die Sonensensoren zuständig ist?

Mit freundlichen Grüßen Jochen

**Comment by zwiebert** [comment]
Danke. Dir auch ein frohes Neues Jahr.

Ich glaube auch, dass die IDs im Prinzip alle noch da sind, aber  irgendwas beim Auslesen oder Anzeigen der Konfiguration hakt.  Werde mir den betreffenden Code die nächsten Tage anschauen und überarbeiten.

mfg Bert

**Comment by zwiebert** [comment]
...die verschwundenen IDs sollten in der neuesten Version 0.11.0.43 nun wieder auftauchen.   Das Webapp Tab für diesen Bereich hat aber noch einige Probleme die dann in der nächsten Beta-Version gefixt werden.

mfg Bert

**Comment by jochenpa** [comment]
Super, klappt wieder. :-)

Kurze Bug-Liste:
- Irgendwie hat Firefox (MacOS) Probleme mit den Listen, es werden nur die ersten 10 Einträge angezeigt (A, 1A, 11, 12, 13, ...).
  (Firefox (Windows) hat das Problem nicht. Eventuell dann doch nicht Dein Bug?)
- Die Namen werden in den Listen erst angezeigt, wenn man jeden Eintrag ein mal aufgerufen hat.
- Der Name für "A" wird dennoch nicht angezeigt.
- In der %%-Anzeige werden die Namen angezeigt, aber NICHT die Positionen (2A, 21, 22, ...)
- In der Log-Anzeige wird gar nichts angezeigt. (Da hätte ich mir viele Debug-Infos erhofft.)

Vielen Dank für Deine tolle Arbeit.

Mit freundlichen Grüßen Jochen

**Comment by zwiebert** [comment]
Schön das es funktioniert. Danke für Dein Feedback.

Im Log-Tab gibt es momentan nur Meldungen des MQTT-Klients.  Ich hab angefangen Deine Liste abzuarbeiten. Melde mich dann wieder.

mfg Bert

**Comment by jochenpa** [comment]
Hallo

Habe schon die 0.11.0.45 installiert, einige Punkte sind schon abgearbeitet, Danke. :-)

Aber was ich eigentlich wollte:
Seit dem Update auf die 0.11 ... (bei mir also erst seit ein paar Tagen) ist die Verbindung zum FHEM nicht mehr optimal.
Genauer gesagt werden die %-Angaben nicht ganz übertragen oder so.
Da steht dann morgens nicht überall 100% (offen), sondern irgendwas zwischen 91% und 99%.
Abends ist es dann nicht überall 0% sondern irgendwas zwischen 9% und 1%.
Wenn ich dann auf einen Eintrag gehe und "stop" oder eine "down"- bzw. "up"-Bewegung anklicke
springt die Anzeige manchmal auf 0% wie es sein soll. Manchmal nicht, dann muss ich erst ein Stück "fahren".

In der MCU wird alles korrekt angezeigt, also jeweils 0% oder 100%.

Das fhem-Modul sollte aktuell sein, es wird kein Update angeboten.
(update check https://raw.githubusercontent.com/zwiebert/tronferno-fhem/master/modules/tronferno/controls_tronferno.txt)
Allerdings wird folgendes angezeigt:
Befehl "version":
No Id found for 10_Tronferno.pm
No Id found for 00_TronfernoMCU.pm
Das wäre dann auch ein Bug? :-)


Mit freundlichen Grüßen Jochen

**Comment by zwiebert** [comment]
...Die fehlerhaften Prozente habe ich hier auch.   Muss ich mal nachschaun wohler das kommt.   Versionsnummern für die Module wären sicherlich auch sinnvoll.  Danke.

mfg Bert

**Comment by zwiebert** [comment]
...die fehlerhaften Prozente in FHEM sind gefixt in Beta Firmware  0.11.0.46.

Noch offen:
   -  Das Firefox/MacOS-Problem
   -  Das Laden aller Namen beim Öffnen der Web-Oberfläsche.
 
Danke fürs melden.

mfg Bert

**Comment by jochenpa** [comment]
Hallo Bert

Wieder danke schön. :-)

Mir ist was zu der Listen-Problematik beim Firefox (MacOS) aufgefallen:
- Man kann die Liste die nur bis zum 10. Eintrag anzeigt mit dem Cursor blind weiter blättern.
- Die Versions-Nummer-Liste auf der Firmware-Seite wird vollständig angezeigt.
Vielleicht hilft das ja, besonders der 2. Punkt ...


Mit freundlichen Grüßen Jochen

**Comment by zwiebert** [comment]
Hallo Jochen, danke für die Info.

in Version 0.11.0.47 hab ich die problematische Select-Liste versucht der Firmware-Versions-Nummer-Liste anzugleichen.  Hat das jetzt vielleicht schon das Problem beseitigt?  Ansonsten versuche ich später noch was anderes.

mfg Bert

**Comment by jochenpa** [comment]
Hallo Bert

Hat an der Listen-Problematik nichts geändert. Aber wie gesagt kann das auch nur ein Firefox-Problem sein.

Mir ist noch was aufgefallen.
Beim Mac-Firefox wird auch die Uhr für die Motor-Laufzeit nicht angezeigt, sondern ein Kästchen mit Fragezeichen.

Und noch ein Bug:
Wenn man in den Motor-Laufzeiten den Motor umschaltet wird erst mal alles mit "0" angezeigt.
Erst wenn man den Tab wechselt und wieder zurück auf die "Uhr" geht werden die aktuellen Werte angezeigt.
Auch ein "Neu Laden" ändert nichts daran dass man erst das Tab wechseln muss.

Mit freundlichen Grüßen Jochen

**Comment by zwiebert** [comment]
Hallo Jochen,

...vieleicht geht es jetzt in 0.11.0.48 mit der Select-Liste unter MacOS?
...ich hab das Uhr-Symbol wieder weggemacht.
...das mit den Laufzeiten habe ich gefixt. Durch den Wechsel auf Svelte haben sich viele solche Fehler eingeschlichen und ich bin wohl betriebsblind.

Danke für dein Feedback.  Ist immer willkommen.

mfg Bert

**Comment by jochenpa** [comment]
Hallo Bert

Liste leider immer noch kaputt (Firefox / MacOS).
Aber nur da, also wirklich nicht so wichtig.
Safari / MacOS geht ja, und unter Windows geht es auch ...

Laufzeiten geht auch bei mir jetzt (wieder).

Vorschlag für den Log-Reiter:
Ich fände es schön, wenn man jeden empfangenen Code und jeden gesendeten Code dort sehen könnte.
Gerne natürlich erst zu aktivieren in den Einstellungen.
Oder wenn nicht da dann im FHEM-Log. Tronferno_Scan existiert ja bereits und legt Logs an.
Mir scheint es als ob da derzeit nur die Codes von Fernbedienungen gelistet werden, warum nicht auch Sonnensensoren?
Dann wären die empfangenen Codes bereits abgedeckt ...


Mit freundlichen Grüßen Jochen

**Comment by zwiebert** [comment]
Hallo Jochen.

Danke für die Rückmeldung. 

...das mit dem Log-Reiter werde ich so mache.  Wobei man dort nie soviel Log-Daten sehen wird, wie im seriellen Terminal. Aber die empfangenen Kommandos und IDs sind kein Problem.

...beim FHEM Modul müsste ich mal bei Gelegenheit schaun, warum das so ist.

mfg Bert

**Comment by jochenpa** [comment]
Hallo Bert

Ich finde die Timer-Programmierung für Wochentage etwas unintuitiv.
Könntest Du da eventuell entweder einen Button hinzufügen, der die Programmierung erklärt.
(Das wäre eigentlich für jede Konfigurations-Seite eine tolle Idee, einen Hilfe-Button mit Dokumentation zu haben.)
Oder noch besser du änderst es so ab, dass man wie bei "Täglich" für jeden Wochentag die Zeit einstellen kann.


Mit freundlichen Grüßen Jochen

**Comment by zwiebert** [comment]
Hallo Jochen,

ja darüber denke ich schon Monate öfter mal nach. Vielleicht werde ich jetzt einfach meinen Wochentagseditor aus der Android-App übernehmen. Dachte mir fällt was besseres ein, aber scheint nicht so. Hatte auch in den letzten Wochen wenig Zeit.

Ich wollte das Userinterface jetzt mehr in Richtung intuitiv umgestalten und wenn immer möglich auf Dokumentation verzichten. Eine leicht zugänglicher Hilfe-Button hört sich aber auch gut an. Muss ich mich mal mit beschäftigen ob das wirklich nötig ist oder ob ich es selbsterklärend hinbekomme.  Das wäre ideal.

Danke für das hilfreiche Feedback,
Bert
